---
name: Yambs Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.12]

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install vmklib>=1.8.0 yambs

      - run: mk dz-sync

      - run: mk yaml python-lint python-sa

      # - name: setup clang 17
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 17
      #     rm llvm.sh

      - run: sudo apt-get install emscripten
      - run: emcc --version
      - run: em++ --version

      - run: sudo apt-get install gcc-13 g++-13 lcov doxygen clang-17 clang-format-17
      # List versions.
      - run: gcc-13 --version
      - run: g++-13 --version
      - run: clang-17 --version
      - run: clang++-17 --version

      - run: mk g
      - run: ninja all format-check
      - run: mk dist docs
        if: github.ref_name != 'master'

      - run: mk release
        if: |
          env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'master'
